#! /usr/bin/env python

#  methlab - A music library application
#  Copyright (C) 2007 Ingmar K. Steen (iksteen@gmail.com)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

if __name__ == '__main__':
  from pymethlab.db import DB
  db = DB()

  import sys

  if len(sys.argv) == 1:
    roots = db.get_roots()
    for row in roots:
      print row[0]
    sys.exit(0)

  action = 'add'
  update = artists = albums = artist_albums = False
  search = []
  for arg in sys.argv[1:]:
    if arg == '--add':
      action = 'add'
    elif arg == '--remove':
      action = 'remove'
    elif arg == '--search':
      action = 'search'
    elif arg == '--update':
      action = 'add'
      update = True
    elif arg == '--artists':
      artists = True
    elif arg == '--albums':
      albums = True
    elif arg == '--artists-albums':
      artist_albums = True
    elif action == 'add':
      db.add_root(arg)
      update = True
    elif action == 'remove':
      db.delete_root(arg)
    elif action == 'search':
      search.append(arg)

  if update:
    db.update()

  if search:
    print 'Search results:'
    for row in db.search(*search):
      print ' %s' % row['path']
      print '  -- Artist: %s' % row['artist']
      print '  -- Album:  %s' % row['album']
      print '  -- Track:  %i - %s' % (row['track'], row['title'])
    print

  if artists:
    print 'Artists:'
    for row in db.get_artists():
      print ' %s' % row['artist']
    print

  if albums:
    print 'Albums:'
    for row in db.get_albums():
      print ' %s' % row['album']
    print

  if artist_albums:
    print 'Artists / albums:'
    for row in db.get_artists_albums():
      print ' %s - %s' % (row['artist'], row['album'])
    print
