#! /bin/sh
dbus-send --session \
          --dest=org.thegraveyard.MethLab \
          --type=method_call \
          /org/thegraveyard/MethLab/Application \
          org.thegraveyard.MethLab.Application.quit
