#! /usr/bin/env python

#  methlab - A music library application
#  Copyright (C) 2007 Ingmar K. Steen (iksteen@gmail.com)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

if __name__ == '__main__':
  import sys

  # Set up a fake _() to aid the error translation.
  def _(s):
    return s

  # Import gtk and check its version and components.
  pygtk_error = None
  try:
    import pygtk
    try:
      pygtk.require('2.0')
    except AssertionError:
      pygtk_error = _('Could not find PyGTK 2.0 installed on your system.')

    try:
      import gtk
      if gtk.check_version(2, 10, 0):
        pygtk_error = _('PyGTK 2.0 version is too old. MethLab requires PyGTK 2.10 or newer.')
      try:
        import gtk.glade
      except ImportError:
        pygtk_error = _('PyGTK 2.10 or newer was found, but the glade component is missing.')
    except ImportError:
      pygtk_error = _('Could not import the PyGTK 2.0 library.')
  except ImportError:
    pygtk_error = _('Could not find PyGTK installed on your system.')

  import locale
  import gettext

  try:
    locale.setlocale(locale.LC_ALL, '')
  except:
    print >> sys.stderr, 'Warning: Cannot set up locale.'

  gettext.textdomain('methlab')
  if pygtk_error:
    print >> sys.stderr, gettext.gettext(pygtk_error)
    sys.exit(-1)

  gtk.glade.textdomain('methlab')

  from pymethlab.gui import MethLabWindow
  win = MethLabWindow()
  gtk.main()
